services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: llm-postgres
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d llmapp"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2
    container_name: llm-redis
    restart: unless-stopped
    env_file:
      - ../.env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-redispass}"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
  redisdata:
