# Generated by Django 4.2.23 on 2025-09-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql=migrations.RunSQL.noop,  # ロールバックで拡張を落とさない
        ),
    ]